name: Get Results ALL

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the release to fetch results from.'
        required: true

jobs:
  get-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge results
        id: merge-results
        run: |
          mkdir -p ./merged-results
          cd ./merged-results
          cp ../scripts/get_all_results_passed_csv.sh .
          cp ../scripts/coleta_dados.py .
          chmod +x get_all_results_passed_csv.sh
          ./get_all_results_passed_csv.sh https://github.com/${{ github.repository_owner }}/os-dependent-python-api/releases/tag/${{ github.event.inputs.release_name }}
          pwd
          ls
        shell: bash

      - name: Upload merged results
        uses: Wandalen/wretry.action@master
        with:
          attempt_delay: 60000 # 1 min
          attempt_limit: 10
          action: softprops/action-gh-release@v1
          with: |
            files: ./merged-results/outputs/final_all.csv
            tag_name: ${{ github.event.inputs.release_name }}
            name: ${{ github.event.inputs.release_name }}
            draft: false
            prerelease: true
            token: ${{ secrets.GITHUB_TOKEN }}
